#!/usr/bin/env nix-shell
#!nix-shell -p nixos-generators -p nix -p coreutils -p bash -p jq -p gh -i bash

set -xeuo pipefail

main() {
  declare -r tag=${1:-nixos-unstable}
  tmp="$(mktemp -d)"
  trap 'rm -rf -- "$tmp"' EXIT
  nixos-generate -o "$tmp/result" -c "pantheon.nix" -f iso -I "nixpkgs=https://github.com/NixOS/nixpkgs/archive/${tag}.tar.gz"

  echo "Automatic release generated by github-actions." >> relnote
  echo "#### Nixpkgs Revision" >> relnote
  curl "https://api.github.com/repos/NixOS/nixpkgs/commits/${tag}" | jq  -r '.sha' >> relnote
  echo "#### SHA-256" >> relnote
  sha256sum $tmp/result/iso/*.iso | awk '{print $1}' >> relnote

  gh release delete "$tag" </dev/null || true
  gh release create "$tag" --title "$tag (build $(date +"%Y-%m-%d"))" -F relnote $tmp/result/iso/*.iso </dev/null
}

main "$@"
