name: "Build"
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron:  '51 2 * * 0'
jobs:
  images:
    strategy:
      matrix:
        tag:
          - nixos-22.05
          - nixos-unstable
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixpkgs-unstable.tar.gz
    - name: Build image
      run: ./build-images.sh "${{matrix.tag}}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
